### ISSUE TITLE
Add "curl" to docker image for healthcheck

### ISSUE THREAD

**Issue by pskillen** [RocketChat/Docker.Official.Image#107]
In previous versions (specifically v2.3.1) the docker image had `curl` which could be used with Docker healthcheck. In the latest v2 (v2.4.11) neither `curl` or `wget` are available so I can't do a healthcheck with the official image.

My guess is this was changed in 9d6297118afd4a6b494b1b82cb4dc7f58e83e45d and caused by the line `apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false`

(Thanks for your work on making this easy for me to deploy/maintain)

**Comment by sampaiodiego** [comment]
hi there.. do you mind sharing how you do your healthcheck? personally I don't think you rely on anything inside the container and you should do the healthcheck externally, but I'd like to see your approach to have better opinion

**Comment by tianon** [comment]
See
https://github.com/docker-library/ghost/issues/208#issuecomment-580967245
for a similar discussion over on the Ghost image.

**Comment by pskillen** [comment]
When we use docker-compose and always add something like the snippet below, which would execute `curl` inside the server container. If curl isn't installed it'll just fail the healthcheck.

```yaml
services:
  server:
    image: rocket.chat:2
    ...
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 30s
      retries: 3
```

We could move to an external check (in fact we do have one from our public-facing load balancer) but that only tells us that _something_ is wrong, not that the server process has died in the container
