### ISSUE TITLE
Support for mongo db ssl connection?

### ISSUE THREAD

**Issue by ripreal** [RocketChat/Docker.Official.Image#134]
I'd like to use specific third-party mongo cloud provider.  The povider that i've chosen  support only one way to make connection - via ssl. For example my connection string looks something similar to this.  
```
mongodb://user:pwd@host:27017/?replicaSet=rs01&authSource=database&ssl=true
```
In addition i also have to pass certificate inside connection options. (*.pem file) My questions is how can i pass certificate file  with rocketchat dockerfile?

Without certificate  when i run rocketchat docker container i get  error:
```
 MongoNetworkError: failed to connect to server [rc1c-5g5vr3tzsfdxjdz9.mdb.yandexcloud.net:27018] on first connect [Error: self signed certificate in certificate chain
 at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
 at TLSSocket.emit (events.js:315:20)
 at TLSSocket._finishInit (_tls_wrap.js:936:8)
 at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
 name: 'MongoNetworkError'
```

My docker-compose:
```
version: '3.6'
services:

  rocketchat:
    image: rocket.chat:latest
    environment:
      - ROOT_URL=http://localhost
      - MONGO_URL=mongodb://user:pwd@host:27017/?replicaSet=rs01&authSource=database&ssl=true
    ports:
      - "3020:3000"

```
