### ISSUE TITLE
we need arm v8 thanks

### ISSUE THREAD

**Issue by cesheji3** [RocketChat/Docker.Official.Image#210]

**Comment by lucasjahn** [comment]
Hi! I actually managed to get that running on ARM with no issues. If you’d like to build it yourself, it’s fairly straightforward. 

Go to the version directory you want to build, and edit the Dockerfile slightly. The key change is to ensure that the correct architecture is specified for your build.

```Dockerfile
FROM debian:bullseye-slim

## Installing Node.js
ENV NODE_ENV production
ENV NODE_VERSION 14.21.3

# Node installation based on official instructions
RUN ARCH="arm64" \ # Change this to 'arm64'

# rest of the dockerfile...
```

The line `RUN ARCH="arm64"` is important here.

Then just run a build of the image and there you go. 

If you are using Docker Compose, make sure to also use the correct image of mogno for your architecture:
```yaml
mongodb:
    image: arm64v8/mongo
```

I already built the image and I will try to make it up-to-date as best as possible:
[https://hub.docker.com/r/edvschleck/rocketchat-arm64](https://hub.docker.com/r/edvschleck/rocketchat-arm64)

As a reference my current compose file:

```yaml
volumes:
  rocketchat_mongodb_data:
    external: true

services:
  rocketchat:
    image: edvschleck/rocketchat-arm64:6.9.2
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: Host(`${DOMAIN}`)
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
    environment:
      MONGO_URL: "${MONGO_URL:-\
        mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        ${MONGODB_DATABASE:-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      MONGO_OPLOG_URL: "${MONGO_OPLOG_URL:\
        -mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      ROOT_URL: ${ROOT_URL:-http://localhost:${HOST_PORT:-3000}}
      PORT: ${PORT:-3000}
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
    depends_on:
      - mongodb
    expose:
      - ${PORT:-3000}
    networks:
      - default
    ports:
      - "${BIND_IP:-0.0.0.0}:${HOST_PORT:-3000}:${PORT:-3000}"

  mongodb:
    image: arm64v8/mongo:${MONGODB_VERSION:-5.0}
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - rocketchat_mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}
    networks:
      - default
```

**Comment by kurokawaikki** [comment]
Hi, I also make a update version of RC to 7.2.0.
Here is the dockerfile you can use.
This is basically official dockerfile with modification of the deno and sharp.

```
FROM node:20-bookworm-slim

ENV DENO_VERSION=1.37.1

RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
  amd64) ARCH='x86_64';; \
  arm64) ARCH='aarch64';; \
  *) echo "unsupported Deno architecture"; exit 1 ;; \
  esac \
  && set -ex \
  && apt-get update && apt-get install -y --no-install-recommends ca-certificates curl unzip && rm -rf /var/lib/apt/lists/* \
  && curl -fsSL https://github.com/denoland/deno/releases/download/v2.1.5/deno-aarch64-unknown-linux-gnu.zip --output /tmp/de>  && echo "f92875c5a77cde3ae7aab27b1f5899481339f1c8be00dc68657adf65578cf4af /tmp/deno-${ARCH}-unknown-linux-gnu.zip" | sha256>  && unzip /tmp/deno-${ARCH}-unknown-linux-gnu.zip -d /tmp \
  && rm /tmp/deno-${ARCH}-unknown-linux-gnu.zip \
  && chmod 755 /tmp/deno \
  && mv /tmp/deno /usr/local/bin/deno \
  && apt-mark auto '.*' > /dev/null \
  && find /usr/local -type f -executable -exec ldd '{}' ';' \
  | awk '/=>/ { print $(NF-1) }' \
  | sort -u \
  | xargs -r dpkg-query --search \
  | cut -d: -f1 \
  | sort -u \
  | xargs -r apt-mark manual \
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false
RUN groupadd -r rocketchat \
  && useradd -r -g rocketchat rocketchat \
  && mkdir -p /app/uploads \
  && chown rocketchat:rocketchat /app/uploads

VOLUME /app/uploads

WORKDIR /app

ENV NODE_ENV=production

ENV RC_VERSION=7.2.0

RUN set -eux \
  && apt-get update \
  && apt-get install -y --no-install-recommends fontconfig \
  && aptMark="$(apt-mark showmanual)" \
  && apt-get install -y --no-install-recommends g++ make python3 ca-certificates curl gnupg \
  && rm -rf /var/lib/apt/lists/* \
  # gpg: key 4FD08104: public key "Rocket.Chat Buildmaster <buildmaster@rocket.chat>" imported
  && gpg --batch --keyserver keyserver.ubuntu.com --recv-keys 0E163286C20D07B9787EBE9FD7F9D0414FD08104 \
  && curl -fSL "https://releases.rocket.chat/${RC_VERSION}/download" -o rocket.chat.tgz \
  && curl -fSL "https://releases.rocket.chat/${RC_VERSION}/asc" -o rocket.chat.tgz.asc \
  && gpg --batch --verify rocket.chat.tgz.asc rocket.chat.tgz \
  && tar zxf rocket.chat.tgz \
  && rm rocket.chat.tgz rocket.chat.tgz.asc \
  && cd bundle/programs/server \
  && npm install --unsafe-perm=true \
  && npm uninstall sharp \
  && npm install --os=linux --cpu=arm64 sharp \
  && apt-mark auto '.*' > /dev/null \
  && apt-mark manual $aptMark > /dev/null \
  && find /usr/local -type f -executable -exec ldd '{}' ';' \
  | awk '/=>/ { print $(NF-1) }' \
  | sort -u \
  | xargs -r dpkg-query --search \
  | cut -d: -f1 \
  | sort -u \
  | xargs -r apt-mark manual \
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
  && npm cache clear --force \
  && chown -R rocketchat:rocketchat /app

USER rocketchat

WORKDIR /app/bundle

# needs a mongoinstance - defaults to container linking with alias 'db'
ENV DEPLOY_METHOD=docker-official \
  MONGO_URL=mongodb://db:27017/meteor \
  HOME=/tmp \
  PORT=3000 \
  ROOT_URL=http://localhost:3000

EXPOSE 3000

CMD ["node", "main.js"]

```

**Comment by lucasjahn** [comment]
@Androids-Dungeon 

Hey. So im also using it with portainer. What I did is: 

- Create a new Stack but via Custom Template
- I added the Environment Variables underneath manually so:
  - RELEASE - 7.6.1
  - ROOT_URL - The url you want to use at the end (im using nginx proxy manager and also assigned a SSL to it later on)
  - MONGODB_VERSION - 6-jammy
  - DOMAIN - your domain without https
- I used this docker-compose setup  (you will see here I have a backup service running which creates a backup on schedule of the rocket chat db)

```
volumes:
  rocketchat_mongodb_data:
    external: true

services:
  rocketchat:
    image: edvschleck/rocketchat-arm64:7.6.1
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: Host(`${DOMAIN}`)
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
    environment:
      MONGO_URL: "${MONGO_URL:-\
        mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        ${MONGODB_DATABASE:-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      MONGO_OPLOG_URL: "${MONGO_OPLOG_URL:\
        -mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      ROOT_URL: ${ROOT_URL:-http://localhost:${HOST_PORT:-3000}}
      PORT: ${PORT:-3000}
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
    depends_on:
      - mongodb
    expose:
      - ${PORT:-3000}
    networks:
      - default
    ports:
      - "${BIND_IP:-0.0.0.0}:${HOST_PORT:-3000}:${PORT:-3000}"

  mongodb:
    image: arm64v8/mongo:${MONGODB_VERSION:-5.0}
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - rocketchat_mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}
    networks:
      - default

  backup:
    image: offen/docker-volume-backup:latest
    container_name: rocker-chat-backup
    restart: unless-stopped
    volumes:
      - rocketchat_mongodb_data:/backup/data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/backups/rocket-chat:/archive
      - /etc/localtime:/etc/localtime:ro
    environment:

      BACKUP_CRON_EXPRESSION: "@daily"
      BACKUP_FILENAME: "rocket-chat-%Y-%m-%dT%H-%M-%S.{{ .Extension }}"
      BACKUP_PRUNING_PREFIX: "rocket-chat-"
      BACKUP_RETENTION_DAYS: 14
```

Let me know if this works for you. 

I will probably upgrade my image in the next days to the newest version. 

Cheers
