### ISSUE TITLE
Can't find migration version 128

### ISSUE THREAD

**Issue by azgul** [RocketChat/Docker.Official.Image#52]
It appears that my instance of [watchtower](https://github.com/v2tec/watchtower) has automagically updated my RocketChat instance to the latest version.

Now it wont launch because of a missing database migration.

```
Will load cache for users
5 records load from users
Will load cache for rocketchat_room
5 records load from rocketchat_room
Will load cache for rocketchat_subscription
14 records load from rocketchat_subscription
Will load cache for rocketchat_settings
720 records load from rocketchat_settings
Updating process.env.MAIL_URL
Will load cache for rocketchat_permissions
80 records load from rocketchat_permissions
Will load cache for rocketchat_roles
11 records load from rocketchat_roles
Starting Email Intercepter...
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
LocalStore: store created at
LocalStore: store created at
LocalStore: store created at
Setting default file store to GridFS
Thu, 21 Jun 2018 16:07:28 GMT connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead at npm/node_modules/connect/lib/middleware/bodyParser.js:56:20
Thu, 21 Jun 2018 16:07:28 GMT connect deprecated limit: Restrict request size at location of read at npm/node_modules/connect/lib/middleware/multipart.js:86:15
Exception in callback of async function: Error: [Can't find migration version 128]
    at Object.Migrations._findIndexByVersion (/app/bundle/programs/server/packages/rocketchat_migrations.js:435:9)
    at Object.Migrations._migrateTo (/app/bundle/programs/server/packages/rocketchat_migrations.js:300:25)
    at Object.Migrations.migrateTo (/app/bundle/programs/server/packages/rocketchat_migrations.js:227:23)
    at xrun.js (/app/bundle/programs/server/app/app.js:7213:25)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /app/bundle/programs/server/app/app.js:12922:1
    at /app/bundle/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>:null:null)
    at /app/bundle/programs/server/boot.js:220:19
    at /app/bundle/programs/server/boot.js:471:5
    at Function.run (/app/bundle/programs/server/profile.js:510:12)
    at /app/bundle/programs/server/boot.js:470:11
```

Can I run the migration manually somehow, and how do I avoid this happening in the future?

My `docker-compose.yml` for context:
```yaml
version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=<snip>
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    depends_on:
      - mongo
    ports:
      - 3000:3000
    networks:
    - proxy
    labels:
    - "traefik.enable=true"
    - "traefik.backend=rocketchat"
    - "traefik.frontend.rule=Host:<snip>"
    - "traefik.docker.network=reverseproxy_default"

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    labels:
      - "traefik.enable=false"
    networks:
    - proxy

networks:
  proxy:
    external:
      name: reverseproxy_default
```
